log-pipeline:
  source:
    otel_logs_source:
      ssl: false
  processor:
  sink:
    - opensearch:
        hosts: [ <OPEN_SEARCH_CLUSTER_ENDPOINT> ]
        insecure: true
        username: <uname>
        password: <pwd>
        index: "otel-logs-%{yyyy.MM.dd}"
metrics-pipeline:
  source:
    otel_metrics_source:
      ssl: false
  processor:
  sink:
    - opensearch:
        hosts: [ "<OPEN_SEARCH_CLUSTER_ENDPOINT>" ]
        insecure: true
        username: <uname>
        password: <pwd>
        index: "otel-metrics-%{yyyy.MM.dd}"
traces-entry-shared-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  buffer:
    bounded_blocking:
      buffer_size: 10240
      batch_size: 160
  sink:
    - pipeline:
        name: "traces-pipeline"
    - pipeline:
        name: "service-map-pipeline"
traces-pipeline:
  source:
    pipeline:
      name: "traces-entry-shared-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 10240
      batch_size: 160
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "<OPEN_SEARCH_CLUSTER_ENDPOINT>" ]
        insecure: true
        username: <uname>
        password: <pwd>
        index_type: trace-analytics-raw
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "traces-entry-shared-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 10240
      batch_size: 160
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: [ "<OPEN_SEARCH_CLUSTER_ENDPOINT>" ]
        insecure: true
        username: <uname>
        password: <pwd>
        index_type: trace-analytics-service-map